### ISSUE TITLE
ETA publication verification code and test data

### ISSUE THREAD

**Issue by Stuffooh** [jayleicn/TVQAplus#10]
Hi,

Is there any ETA when the verification code along with test data will be published?

Looking forward to seeing the additional code and data ;)

**Comment by jayleicn** [comment]
Hi @Stuffooh,

Sorry for the late reply. In case you haven't noticed, the verification code is uploaded in this repo, tets data is also made available at http://localhost:63342/tvqa_webpage/download_tvqa_plus.html.

Best,
Jie
