### ISSUE TITLE
Confusion finetuning format for BERT

### ISSUE THREAD

**Issue by Stuffooh** [jayleicn/TVQAplus#11]
Hi, I'm a little bit confused about the following and was hoping you could shed some more light on my issue.

In one of the comments on another issue it is mentioned that a single document is constructed with both subtitles and QA. However the tvqa+ dataset contains two .h5 files: "bbt_qa_s_tokenized_bert_sub_qa_tuned_new_qid.h5" and "bbt_sub_s_tokenized_bert_sub_qa_tuned.h5". This gives me the impression  subtitles and QA are finetuned separately instead of together with one document.  

The comment I'm refering to is quoted below:

Hi @aurooj ,

I used the code provided by hugging face to finetune BERT, as in https://github.com/huggingface/transformers/blob/master/examples/run_lm_finetuning.py. Feature extraction code is also based on it.

For your question,  I finetuned both subtitles and QA with the two tasks. A single document is constructed as:
```
subtitle_sentence1.
...
subtitle_sentenceN.
question.
correct_answer.
```

`question` will be the next sentence of `subitile_sentenceN`, etc.

_Originally posted by @jayleicn in https://github.com/jayleicn/TVQAplus/issues/6#issuecomment-550598730_

**Comment by jayleicn** [comment]
Hi @Stuffooh, 

Please see my updated reply at https://github.com/jayleicn/TVQAplus/issues/6#issuecomment-576048617. 

 Best,
Jie
