### ISSUE TITLE
Fine-tuning format and data loading

### ISSUE THREAD

**Issue by Stuffooh** [jayleicn/TVQAplus#14]
Hi,

After our discussion in #13 I have done some testing and changed my code based on your suggestions. However, the results I get are still 5-6% lower when I use my own extracted features compared to the original ones.

I have been thinking about it for a while and feel like at this point the feature extraction is not the problem. I think the problem might be in the way I fine-tune BERT before feature extraction. I will give a quick overview how I fine-tune BERT and I was hoping you could take a look at it and point out any problems.

I use the following document structure for the training data to fine-tune BERT:

```
Sub_sentenceA. Sub_sentenceB. Sub_sentenceC.

Question.
Correct answer.


Sub_sentenceA. Sub_sentenceB. Sub_sentenceC.

Question.
Correct answer.


Sub_sentenceA. Sub_sentenceB. Sub_sentenceC.

Question.
Correct answer.
```

I replace all the `<eos> tokens` with a white space and subtitle sentences which are longer than 512 tokens I remove the last word of the subtitle until the tokenized subtitles are <512 so they fit in the model.

I load the training data as follows:

```
class LineByLineTextDataset(Dataset):
    def __init__(self, tokenizer: PreTrainedTokenizer, args, file_path: str, block_size=512):
        assert os.path.isfile(file_path)
        # Here, we do not cache the features, operating under the assumption
        # that we will soon use fast multithreaded tokenizers from the
        # `tokenizers` repo everywhere =)
        logger.info("Creating features from dataset file at %s", file_path)

        if args.do_extract:
            with open(args.extracted_data_file, "r") as input_data:
                input_data = json.load(input_data)
            lines = list(input_data.values())
        else:
            with open(file_path, encoding="utf-8") as f:
                lines = [line for line in f.read().splitlines() if (len(line) > 0 and not line.isspace())]
        for i , item in enumerate(lines):
            while len((tokenizer.encode(item))) > args.block_size:
                item = item.rsplit(' ', 1)[0]
            lines[i] = item
        self.examples = tokenizer.batch_encode_plus(lines, add_special_tokens=True, max_length=block_size)["input_ids"]
    def __len__(self):
        return len(self.examples)

    def __getitem__(self, i):
        return torch.tensor(self.examples[i], dtype=torch.long)
```

I fine-tune BERT-base uncased for 3 epochs with the default  hyper parameters provided by the Huggingface's example fine-tune script.

If you spot any noticeable differences in the data format, the way the data is loaded or perhaps some hyper parameters please share so I can further optimize my code and hopefully reproduce your results. It has been a good learning experience so far and hope these github issues will help fellow researchers in the future to push the results on the TVQA+ dataset ;)

**Comment by jayleicn** [comment]
Hi @Stuffooh,

As in this issue, https://github.com/jayleicn/TVQAplus/issues/6#issuecomment-576048617

The fine-tuning documents are organized as
```
subtitle_sentence1.
...
subtitle_sentenceN.

question.
correct_answer.
```

Which is different from what you have done -- multiple sub sentences as a single sequence.

In terms of finetuning procedure, I finetune the `bert-base-uncased` model with batch_size 32, max_seq_length 128, learning_rate 3e-5, num_train_epochs 3.

Best,
Jie

**Comment by Stuffooh** [comment]
Hi @jayleicn,

Thanks for your reply and patience. 

You mention fine-tuning documentS (not sure if a typo or you actually use multiple fine-tuning documents?

I will take another look at my fine-tuning document and the hyperparameters meanwhile.

Thanks for your input.

Kind regards,

Kevin

**Comment by shinying** [comment]
Hi @jayleicn 

Thanks for the clarification in the discussion above, but the finetuning example provided by Huggingface that you mentioned in #6 has been removed while in [this article](https://huggingface.co/blog/how-to-train), the author said that run_lm_finetuning.py has been replaced by [run_language_modeling.py](https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_language_modeling.py). 

However, this script doesn't implement the NSP task, so could you please share more details about the policy on constructing input sentences for NSP? For example, how did you create negative samples? Were negative paired sentences sampled from different videos or sentences in the same videos with wrong orders?

Will appreciate your reply.

**Comment by jayleicn** [comment]
Hi @shinying, 

You can take a look at my forked repo here: https://github.com/jayleicn/pytorch-pretrained-BERT/tree/master/examples. It contains some of the scripts that I used for finetuning and extracting features. Though it is outdated quite a lot, you may still get some useful info from it. Hope this helps!

Best,
Jie

**Comment by shinying** [comment]
Thank you for the prompt reply! But the page seems to be removed or only allows private access (?)

**Comment by jayleicn** [comment]
Oh sorry, my bad. Could you try again?

**Comment by shinying** [comment]
Thanks for sharing! It helps a lot.
