### ISSUE TITLE
data preprocess

### ISSUE THREAD

**Issue by zongshenmu** [jayleicn/TVQAplus#17]
I know your dataset is similar to tvqa as well as the preprocess. But there are spatial bounding boxes in the tvqa+, can you provide the detail processing code?

**Comment by jayleicn** [comment]
Hi @zongshenmu,

We did not do any preprocessing for the bounding boxes. Could you elaborate on what you are after? For video/text feature extraction etc, you may refer to this issue https://github.com/jayleicn/TVQAplus/issues/18. 

Best,
Jie

**Comment by zongshenmu** [comment]
Appreciate your response. I am fused about your processed boxes in the tvqa_plus_x_preprocessed.json. The number of regions(bounding boxes) in per frame is different, while your paper mentioned that the number is top20. How can you use bottom-up top-down model to get different proposals in every frame?
