### ISSUE TITLE
Feature Extraction Steps

### ISSUE THREAD

**Issue by engindeniz** [jayleicn/TVQAplus#18]
How can I train your code with the TVQA dataset? Could you also provide the codes to extract features for frames and subtitles, please?

**Comment by jayleicn** [comment]
Hi @engindeniz,

For object features in frames, we used the code here: https://github.com/peteanderson80/bottom-up-attention
For subtitle/QA text features, we used a similar process as in https://github.com/jayleicn/TVRetrieval/tree/master/utils/text_feature, you may also refer to related issues in this repo such as  https://github.com/jayleicn/TVQAplus/issues/14.

Best,
Jie

**Comment by jayleicn** [comment]
For PCA, we used here https://scikit-learn.org/stable/auto_examples/decomposition/plot_incremental_pca.html.
