### ISSUE TITLE
Regional visual feature的提取是否需要原图呀？

### ISSUE THREAD

**Issue by Curry-AI** [jayleicn/TVQAplus#19]
https://github.com/peteanderson80/bottom-up-attention#demo 

根据这个项目README中DEMO板块的描述，如果需要提取一个图片的区域特征，应该是需要原图的

但是TVQA数据集目前是没有放开原图下载吗？

那请问区域特征如何才能提取呢？

**Comment by jayleicn** [comment]
Hi @Mao-JianGuo，

The TVQA video frames are available to download as described here: https://tvqa.cs.unc.edu/download_tvqa.html#tvqa-download-4.

Best,
Jie

**Comment by Curry-AI** [comment]
非常感谢 @jayleicn，
我已经填写了申请表~

关于区域特征的提取，有一点疑问，希望您可以解答一下
3.3 Regional visual feature: please follow the instructions here to do the extraction. Currently, we do not plan to release it, due to its size.
提取区域特征的项目是bottom-up-attention，是使用tools/generate_tsv.py来提取吗？ load_image_ids 需要如何改写呢？以及最终存储的区域特征格式是怎样的呢？

非常感谢

**Comment by jayleicn** [comment]
Yes, the features are extracted with https://github.com/peteanderson80/bottom-up-attention/blob/master/tools/generate_tsv.py. We have provided features used in this project in https://github.com/jayleicn/TVQAplus#training-and-evaluation. If you want to extract features yourself, you can refer to the format of the shared feature file.
