### ISSUE TITLE
some confusions about this paper

### ISSUE THREAD

**Issue by lixiangpengcs** [jayleicn/TVQAplus#2]
Hello, I have some confusions about this paper and I will appreciate it if you can help me to understand:
1. The video representation length is T and the subtitle length is also T as shown in figure 5. But it is obviously the number of subtitle is less than frame number. I want to know how to organize the subtitle data?

**Comment by lixiangpengcs** [comment]
2. Do your span predictor predict the start index and end index of located frame?
Hope you can release your code soon!

**Comment by jayleicn** [comment]
Hi @lixiangpengcs,

1, Each frame is paired with two subtitle sentences that are closest to it.
2, Yes, the span predictor predicting the start/end indices.

**Comment by lixiangpengcs** [comment]
Thanks for your reply. I saw that you refine time stamps on BBT series in TVQA+ dataset. Do you do time stamp refinement on the whole TVQA dataset?

**Comment by jayleicn** [comment]
Nope, only on BBT. 

So the TVQA dataset still comes with old ts (even for the BBT data), while the TVQA+ comes with refined ts. The old ts is good for the purpose as we showed in TVQA+ paper adding old ts helps to achieve better accuracy on TVQA dataset.
