### ISSUE TITLE
Unable to unzip your feature file

### ISSUE THREAD

**Issue by Noahsark** [jayleicn/TVQAplus#5]
Hi Lei,

Thank you so much for releasing the code. I tried to download your feature file from google drive but fail to unzip it. It seems the file was broken. Could you please check this issue? 

Thanks.

**Comment by Noahsark** [comment]
Solved. It's turn out to be a gzip file instead of zip.

**Comment by jayleicn** [comment]
Sorry for the inconvenience, I changed the suffix to `.tar.gz`.
